local RECIPE = Clockwork.recipe:New("HK USP Blueprint");
		RECIPE:Require("junk_screwdriver");
		RECIPE:Require("junk_screws", 4);
		RECIPE:Require("part_uspslide");
		RECIPE:Require("part_uspsight");
		RECIPE:Require("part_uspcasing");
		RECIPE:Output("m9k_usp");
		RECIPE:Output("junk_screwdriver");
		RECIPE.description = "A blueprint describing how to assemble a HK USP Sidearm.";
		RECIPE.model = "models/error.mdl";
RECIPE:Register();